language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_deploy: npm install now --no-save 
script:
  - npm run build
deploy:
  - provider: script 
    script: now --token $NOW_TOKEN build/ --public
    skip_cleanup: true
    on:
      master: true
