language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_deploy: npm install now --no-save 
install:
  - npm install
  - npm run build
deploy:
  - provider: script 
    script: 
      - npm run deploy